name: Comment on Jira issue

on:
  pull_request:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on Jira issue
        run: |
          ISSUE_KEY=$(echo ${{ github.event.pull_request.title }} | grep -o '[A-Z0-9]\+-[0-9]\+')
          COMMENT="Pull request opened: ${{ github.event.pull_request.html_url }}"
          
          curl -u sourabh.ruhella@walmart.com:${{ secrets.JIRA_API_TOKEN }} \
            -X POST \
            -H "Content-Type: application/json" \
            --data "{ \"body\": \"$COMMENT\" }" \
            https://sourabhruhella.atlassian.net/rest/api/3/issue/$ISSUE_KEY/comment
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}